import os
import google.generativeai as genai

# Configure Gemini
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# ✅ Stable & supported model
MODEL_NAME = "models/gemini-1.5-pro"

def ask_gemini(prompt: str) -> str:
    """
    Safe Gemini wrapper.
    Never crashes the app.
    """

    try:
        model = genai.GenerativeModel(MODEL_NAME)
        response = model.generate_content(prompt)

        if not response or not response.text:
            return "No response generated by AI."

        return response.text.strip()

    except Exception as e:
        return f"AI unavailable. Reason: {str(e)}"
